---
#- name: Installing git-flow packages using apt
#  become: true
#  apt:
#    pkg: "git-flow"
#    update_cache: yes
#    state: latest
#  when: ansible_distribution == 'Ubuntu'

#- name: Installing git-flow packages using yum
#  become: true
#  yum:
#    pkg: "git-flow"
#    update_cache: yes
#    state: latest
#  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'


#- name: Installing git-flow packages using pacman
#  pacman:
#    name: "git-flow"
#    state: present
#  when: ansible_distribution == 'MacOSX'

- name: Installing git-flow packages
  become: true
  package:
    name: "git-flow"
    state: present
